development:
  adapter: mysql
  encoding: utf8
  database: pin-website-development
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  encoding: utf8
  database: pin-website-test
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  database: pin-website
  username: root
  password: root
  pool: 5
  timeout: 5000
